apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: mahjong-solitaire
spec:
  serviceName: redis-replica
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      nodeSelector:
        nodepool: data
      tolerations:
        - key: "nodepool"
          operator: "Equal"
          value: "data"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: redis
                topologyKey: kubernetes.io/hostname
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --appendfilename
            - appendonly.aof
            - --dir
            - /data
            - --replicaof
            - redis-master-0.redis-master
            - "6379"
            - --bind
            - 0.0.0.0
            - --protected-mode
            - "no"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
