apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: mahjong-solitaire
spec:
  serviceName: redis-master
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          args:
            - redis-server
            - --appendonly
            - "yes"
            - --appendfilename
            - appendonly.aof
            - --dir
            - /data
            - --bind
            - 0.0.0.0
            - --protected-mode
            - "no"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
