apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: mahjong-solitaire
data:
  sentinel.conf: |
    port 26379
    bind 0.0.0.0
    protected-mode no
    sentinel monitor mahjong-master redis-master-0.redis-master 6379 2
    sentinel down-after-milliseconds mahjong-master 5000
    sentinel failover-timeout mahjong-master 10000
    sentinel parallel-syncs mahjong-master 1
    sentinel resolve-hostnames yes
