apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-master-pdb
  namespace: mahjong-solitaire
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: redis
      role: master
